name: 'project_nexus'
version: '1.0.0'
config-version: 2

profile: 'project_nexus'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files

models:
  project_nexus:
    staging:
      +materialized: view
    marts:
      +materialized: table
