name: 'fintech_data_engine'
version: '1.0.0'
config-version: 2

profile: 'fintech_data_engine'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files

models:
  fintech_data_engine:
    staging:
      +materialized: view
    marts:
      +materialized: table
